# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5ef0d4f96a366d8c6ffebf64866014ff008640a579561419ff50ee50031161289ba2e7409b38163c551725cbafb6bacd6178e11144deaaa0bc44395e13a53247

test:
  secret_key_base: 6124ea1efa6d5463ccc476da83d3bef0b080cef81447f2b2d326f66e45789a3fd7cda13b275fe396577961a66a11d1553f88ef1468de902dd3f4553e25ac7bad

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
